name: astro-ai
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - streamlit=1.28.1
  - numpy=1.24.3
  - pandas=2.0.3
  - scipy=1.10.1
  - matplotlib=3.7.2
  - seaborn=0.12.2
  - astropy=5.3.4
  - h5py=3.9.0
  - pip
  - pip:
      - openai==1.3.5
