name: astro-ai
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy>=1.24.0
  - pandas>=2.0.0
  - matplotlib>=3.7.0
  - scipy>=1.10.0
  - seaborn>=0.12.0
  - astropy>=5.3.0
  - h5py>=3.8.0
  - streamlit>=1.28.0
  - cython
  - pip
  - pip:
    - bagpipes>=1.0.0
    - openai>=0.27.0
    - pytest>=7.0.0
    - black>=23.0.0
    # Optional astronomical packages (uncomment if needed)
    # - tools21cm
    # - nautilus-sampler
    # - "git+https://github.com/21cmfast/21cmFAST.git"  # Linux/WSL only