#############################################
# Streamlit Secrets for Astro-AI            #
#                                           #
# DO NOT COMMIT REAL API KEYS               #
# This file is excluded via .gitignore (will add if missing).  
# Replace PLACEHOLDER with your actual key locally or in deployment. 
#############################################

# OpenAI API Key used by OpenAIAssistant (api/openai_integration.py)
OPENAI_API_KEY = "PLACEHOLDER_REPLACE_WITH_REAL_KEY"

# You can add other secrets below, e.g. database credentials:
# DB_USER = "astro_user"
# DB_PASSWORD = "super_secret"

# Rotation procedure:
# 1. Generate new key in provider dashboard
# 2. Update value here (or deployment secret store)
# 3. Restart Streamlit app
# 4. Delete old key in provider dashboard
