# Streamlit secrets configuration
# Add your OpenAI API key here when available

[openai]
OPENAI_API_KEY = "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"

# OpenAI features are now enabled